### ISSUE TITLE
目前的sendkeys()会调起系统键盘处理逻辑复杂多变，希望能支持utf7输入法简化处理逻辑

### ISSUE THREAD

**Issue by Yinxl** [macacajs/UIAutomatorWD#15]
安卓真机上系统输入法和自定义输入法多种多样，用sendkeys调起键盘后失败率很高，建议增加utf7输入法的支持，这样在输入的时候可以不用吊起键盘，从而减少对应的处理

**Comment by qichuan** [comment]
@Yinxl  在WD层无论是用`UiDevice#pressKeyCode()`，还是`adb shell input keyboard text`来执行sendkeys(), 在安卓真机上使用时都会调用和显示系统键盘。建议在sendkeys()后使用keys(`${KEY_MAP.ESCAPE}`)来隐藏系统键盘。
