### ISSUE TITLE
failed to resolve xpath on real devices

### ISSUE THREAD

**Issue by SamuelZhaoY** [macacajs/UIAutomatorWD#18]
At login page of macaca sample android app, the uiautomator fails to resolve xpaths retrieved from App-Inspector.  e.g.
```
//android.widget.FrameLayout[2]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[2]/android.widget.Button[1]
```

After attaching debug point for uiautomator, the following exception is trapped:
![image](https://user-images.githubusercontent.com/8198256/31165683-8c39fcbe-a91e-11e7-8d29-beac0148086a.png)

**Comment by SamuelZhaoY** [comment]
Seems the previous issue has been fixed. However as I upgrade the macaca-android and app-inspector to the recent version, it is found that for low API version simulators, everytime execute 'source' from app-inspector, the UIAutomator restarts..

![2017-10-12 9 24 38](https://user-images.githubusercontent.com/8198256/31474726-3018a61c-af2f-11e7-999d-c5d153341651.png)

and the source returns "0"

![2017-10-12 9 25 20](https://user-images.githubusercontent.com/8198256/31474750-4ddabc58-af2f-11e7-9a7d-9251923d992a.png)

**Comment by SamuelZhaoY** [comment]
@qichuan @xudafeng

**Comment by qichuan** [comment]
Duplicate issue of https://github.com/alibaba/macaca/issues/714, and it is already fixed in https://github.com/macacajs/app-inspector/pull/148
