### ISSUE TITLE
permissionPattern == "undefined"

### ISSUE THREAD

**Issue by darkrift** [macacajs/UIAutomatorWD#30]
On my android device, the call to args.getString("permissionPattern") in UIAutomatorWD.MacacaTestRunner() returns "undefined" which results in an exception when trying to parse it as a JSONArray.

The following code fixed it 
```
String perms = args.getString("permissionPattern");
if (!perms.equals("undefined")) {
  JSONArray permissionPatterns = JSON.parseArray(perms);
  skipPermission(permissionPatterns, 15);
}
```

**Comment by darkrift** [comment]
Android version 4.4.4 on a Samsung E Lite (SM-T113)

**Comment by xudafeng** [comment]
https://github.com/macacajs/UIAutomatorWD/commit/e559d3a025b2e6bbbf834137d0755efe7e653fca

**Comment by darkrift** [comment]
Sorry forgot to follow up but that works and is much better than ehat I did. Didn’t really had the time to understand the mechanics and locally fixed it. Thanks for the fix :)
