### ISSUE TITLE
使用drag方法时，如果是两个点的滑动需要传duration，如果是三个点以上的滑动则需要传step，与文档不一致

### ISSUE THREAD

**Issue by quxiaozha** [macacajs/UIAutomatorWD#43]
再调用/wd/hub/session/:sessionId/actions，type传drag时，如果是两个点的滑动需要传duration，如果是三个点以上的滑动则需要传step，与文档不一致。

**Comment by adadale** [comment]
文档已更改，https://macacajs.com/zh/helpful-settings

**Comment by quxiaozha** [comment]
再次检查了一下，发现是个小bug，ActionController的233行steps = action.getInteger("steps");这个如果没有传steps，会返回null，导致int类型的steps=null时报NullPointerException，改成steps = action.getIntValue("steps");就ok了，没传的时候会返回0，可以做到不管几个点都只需要传duration即可，已提交pr。

**Comment by xudafeng** [comment]
https://github.com/macacajs/UIAutomatorWD/commit/bc42d9e06393f41c0b1a755ebf6c002709ded456
