### ISSUE TITLE
按钮1->按钮2->按钮3->按钮4,在点击按钮3的时候找不到控件。但如果我按 按钮3->按钮4这样来点击，却能找到。代码一样。调用uiautomator。哪位大佬帮忙看看

### ISSUE THREAD

**Issue by woals** [macacajs/UIAutomatorWD#55]
![image](https://user-images.githubusercontent.com/16473981/53809945-cf767c00-3f90-11e9-8e97-46acf6af009d.png)

**Comment by paradite** [comment]
请到这里提issue，并使用规范的格式，详细描述一下问题：
https://github.com/alibaba/macaca/issues/new
